// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI9LdX6D2MkxSySZ8dwobSGaBdBmW-Ytk',
    appId: '1:414752392085:web:3326a5d2baadd48ed5ac9c',
    messagingSenderId: '414752392085',
    projectId: 'eemedia-5a142',
    authDomain: 'eemedia-5a142.firebaseapp.com',
    storageBucket: 'eemedia-5a142.firebasestorage.app',
    measurementId: 'G-31X6HW3Q8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5A0DxFDLsNmEq2AOTwfe21soTTxsANlM',
    appId: '1:414752392085:android:dd763ba6b8a08588d5ac9c',
    messagingSenderId: '414752392085',
    projectId: 'eemedia-5a142',
    storageBucket: 'eemedia-5a142.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeGJo4m5qfN6f24krbKDGUM6LvKftMiM8',
    appId: '1:414752392085:ios:360d61e359dfa91ed5ac9c',
    messagingSenderId: '414752392085',
    projectId: 'eemedia-5a142',
    storageBucket: 'eemedia-5a142.firebasestorage.app',
    iosBundleId: 'com.example.eemedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeGJo4m5qfN6f24krbKDGUM6LvKftMiM8',
    appId: '1:414752392085:ios:360d61e359dfa91ed5ac9c',
    messagingSenderId: '414752392085',
    projectId: 'eemedia-5a142',
    storageBucket: 'eemedia-5a142.firebasestorage.app',
    iosBundleId: 'com.example.eemedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI9LdX6D2MkxSySZ8dwobSGaBdBmW-Ytk',
    appId: '1:414752392085:web:ffc00faf3f6f2651d5ac9c',
    messagingSenderId: '414752392085',
    projectId: 'eemedia-5a142',
    authDomain: 'eemedia-5a142.firebaseapp.com',
    storageBucket: 'eemedia-5a142.firebasestorage.app',
    measurementId: 'G-1TQ96EBCSE',
  );
}
